title: DataHarness
description: A unified abstraction layer for multiple table sources
baseurl: /
url: https://www.dataharness.org

theme: minima

plugins:
  - jekyll-feed

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - vendor/

markdown: kramdown
