name: Maven Test and Build

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        id: setup-java-17
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Java 25
        uses: actions/setup-java@v4
        id: setup-java-25
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build project with Java 25
        run: mvn clean install -DskipTests -T1C -U
        env:
          JAVA_HOME: ${{ steps.setup-java-25.outputs.path }}

      - name: Run tests with Java 17
        run: mvn test -pl dataharness-server -T1C
        env:
          JAVA_HOME: ${{ steps.setup-java-17.outputs.path }}
