name: Maven Build and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run spotless
        run: mvn spotless:apply -T4

      - name: Build project
        run: mvn clean install -DskipTests -T4 -U

      - name: Deploy to Maven Central
        run: |
          mvn deploy \
            -Dserver.username=${{ secrets.SONATYPE_USERNAME }} \
            -Dserver.password=${{ secrets.SONATYPE_PASSWORD }}

      - name: Build and push Docker image with Jib
        working-directory: ./dataharness-server
        run: |
          mvn jib:build \
            -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
            -Djib.to.auth.password=${{ secrets.DOCKER_TOKEN }}
